name: poverty 
channels:
- conda-forge
- defaults
dependencies:
- matplotlib=2.0.2
- numpy=1.13.3
- pip=9.0.1
- pandas=0.20.3
- ipython=6.1.0
- jupyter=1.0.0
- scikit-learn=0.19.0
- scipy=0.19.1
- progressbar2=3.34.3
- jupyterlab
- tqdm
- pip
pip:
  - imbalanced-learn
